# ReCode by @Hiroshi
# FROM Hiroshi-Userbot <https://github.com/UserbotMaps/Hiroshi-Userbot>
# KONTOLLLLLLL GA USAH DI APUS MEMEK CREDIT NYA 

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP, CMD_HANDLER as cmd
from userbot.utils import edit_or_reply, joo_cmd

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================


@joo_cmd(pattern="ybk(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**YAILAH BANG KOSA KATA LU KOSA KATA YG UDH BOSEN GUA DENGAR LU BLG MAK BAPAK GUA DH MENINGGAL YAILAHH JGN MALU MALUIN HARGA DIRI LU MENDING LU FOKUS URUSIN MAK BAPAK LU UDH PENYAKITAN MAK LU YG KENAK ASAM URAT LAH KANKER PAYUDARAH LAH KANKER RAHIM LAH TUH NTR LAGI STADIUM 4 MENINGGAL.MAK LU TERUS BAPA LU TUH YG APA APA KNP SERANGAN JANTUNG STRUKK GA BISA NGOMONG LU URUSIN JGN MALAH KABUR DRI RUMAH GA NGURUSIN ORTU LU MALU BEGO ORTU LU GA PUNYA DUIT BUAT OPERASI KRNA KERJANYA KMRN AJ NGULI UDH GA BISA NGULI PENGANGGURAN LU MALAH KABUR NUMPANG DI KOSAN TEMEN LU MAK BAPAK LU LU LETAK DI PANTI JOMPO YA KAN GUA MAH TAU KRNA GUA JUMPA AMA LU, LU BENTAK BENTAK MAK BAPAK DIH KSIAN ANAK GA TAU DIRI**"
                        )


@joo_cmd(pattern="yba(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**LAH BOSEN APAAAN TOLOL LO LIAT KOSA KATA LO YANG UDAH BASI TOLOL YANG BANYAK DI PAKE ORANG SAMA KAYA EMAK LO YANG SERING DI PAKAI ORANG TOLOL, MAK NYA UDAH KAYA ROKOK SATU BATANG BISA DI PAKE RAME RAME YAKAN ITU MAK LO TOLOL KASIAN DIA JAM SEGINI BELOM PULANG KARENA MASI CARI UANG PAKAI MEMEK NYA YANG UDAH BECEK ITU TOLOL APA LO KAGA KASIAN BEGO LIAT MAK LO YANG KEK GITU MENDINH MAMAK LO SURUH KERJA YANG BENER TOLOL JANGAN NGELONTE MULU APALAGI BAPAK LO KAN YANG SUKA MALING KOTAK AMAL DI MASJID BEGO KARENA BAPAK LO GABISA APA APA TOLOL BAPAK LO AJA LIAT EMAK EMAK TUA YANG LEWAT PINGGIR JALAN LANGSUNG SAGAPUNG MEGANG KONTOL KAN BEGO BOCAH TOLOL ,SAMA KAYA ANAK NYA YANG SUKA DENGER SUARA CEWE DIKIT AJA LANGSUNG SANGE KAN TOLOL , MAKANYA PUNYA MUKA ITU GANTENGAN DIKT NAPA BIAR GA KAYA GITU TOLOL BIARLO BISA NGTD GUA TAU KONTOL LO BENGKOK KAN JADINYA SUSAH NGTD ,LADENIN BOCAH BOCAH KAYA LO MAH SAMBIL NGUDUD TOLOL KARENA APA KARENA LO KAGA ADA KERAS KERAS NYA TOLOK SEGITU SEGITU AJA BEGOGUA TAU LO AJA KALO NGETIK LAMA BANGT KARNA JARI JARI LO LO KORENGAN KENA KUTILAN SEMUA PENYAKIT ADA DI BADAN LO DAN DIKIT**")


@joo_cmd(pattern="babdi(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**BABU DI PASAR YG SUKA MANGGUL MANGGULIN BERAS, YANG DI GAJINYA CUMAN GOCENG DOANG, GOCENG DOANG CUKUP BUAT BELI APA NGENTOD, GOCENG DOANG CUKUP BUAT BELI TAHU BULAT SAMA SOTONG GORENG DOANG TOLOL, HADEUH GINI NI YANG MANUSIA KALO DI LAHIRIN ITU BUKAN DARI LUBANG MEMEK TAPI DARI LUPANG BOOL, JADI KELAKUANNYA KEK TAI, OH IYA SELAIN LU SUKA MANGGUL MANGGULIN BERAS DI PASAR, LU JUGA SUKA MINTA MINTA DUIT DI PINGGIR JALAN BEGO, YANG KATANYA BUAT SUMBANGAN MASJID, PADAHAL BUAT LU MAKAN SAMA KELUARGA LU TIAPA HARI TOLOL, GINI AJA DEH MENDING LU SEKOLAH YG BENER DAH, DARI PADA LUNTANG LANTUNG KAGA JELAS, MAKANNYA KALO IDUP ITU HARUA PUNYA TUJUAN BEGO, UDH IDUP KAGA OUNYA TUJUAN GAGAL LAGI DI CIPTAIN TUHAN NYA, HADEUH MIRIS BET MIRIS ANJ**"
                        )


@joo_cmd(pattern="bky(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**BOCAH KAMPUNG YANG RUMAHNYA DI PELOSOK DEKET KANDANG KAMBING KEK GINI NI, MUKA LU AJA MASIH MUKA MUKA KUNO TOLOL, MUKA MUKA JAMAN PENJAJAHAN  GINI NI, JADI KAMPUNGAN LU ITU TOLOL, GUA KASIH TAU LAGI NI YA, UDH DEK MENDING LU SEKOLAH YANG BENER DLU, NTAR DI KASIH PERALATAN YG LEBIH LAYAK SAMA EMAKNYA YA, APA MAU GUA KASIH PERALATAN NYA? CUIH GA DEH NAJIS KALO NGASIH SAMA ANAK HARAM KEK LU, APAAN MUKA LU AJA KEK DUDUKAN KLOSET TOLOL, DUDUKAN KLOSET YANG CUMAN DI DUDUKIN DOANG BUAT BUANG TAI BEGO, MAKANNYA HIDUP ITU HARUS AGAK KERENAN DIKIT, CARA HIDUP JAMAN DLU MASIH AJA LU PAKE TOLOL, KALO UDH KAGA ADA KOSA KATA UDH NGOMONG AJA, DARI PADA LU GETAR GETIR DI KASIH KOSA KATA YG LEBIH DALEM KAN, GUA TAKUNYA KALO DI KASIH KOSAKATA YG LEBIH DALEM, TAKUTNYA KE UGD YA KAN, TAKUNYA GANTUNG DIRI, GOROK LEHER, HADEUH KASIAN BET GUA LIAT IDUP KEK LU!**"
                        )


CMD_HELP.update(
    {
        "war4": f"𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}ybk\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}yba\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}babdi\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}bky\
        \n↳ : lihat sendiri\
        \n↳ **COBAIN AJA SAMA LU KONTOL!**.\
    "
    }
)
