# ReCode by @Hiroshi
# FROM Hiroshi-userbot <https://github.com/UserbotMaps/Hiroshi-Userbot>
# KONTOLLLLLLL

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP, CMD_HANDLER as cmd
from userbot.utils import edit_or_reply, joo_cmd

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================


@joo_cmd(pattern="obm(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**OH BAHAS MUKA SIAPA YG PALING HINA NEH?,EH TOLOL MUKA LO AJ LEBIH HINA BEGO GUE KASIH TAU MUKA LO AJA MUKA MUKA PENCABUL TOLIL UDH MUKA BINTIKAN JERAWATAN UDH KEK MAU KENA TUMOR MUKA ANJ.MENDING LO URUSIN MAK LO BEGO MEMEKBY UDH LEDESAN NANAHAN EMG G KASIAN?YAILAH LH G KASIAN ANAKNY AJ AUTIS G JLS ASAL USULNY DRI MANA ORG LO AJ DITEMUIN MAK LO DI TEMPAT SAMPAH LO AJ ANK HARAM HASI EWEAN BAPA ORG MAK ORG LO KAN ASLINY GPNYA BAPA TOLOL,NIH GUE CERITAIN KISAH HIDUP LO NIH YE,MAK LO ITU GAADA YANG TAU DMNA APA LAGI BAPALO LO KAN HASIL ZINAH HASIL HUB TERLARANG NAH LO DI BUANG DI TONGSAMPAH NAH MAK LO YG SKRG KASIAN SAMA LO MKNY DI PUNGUT UDH LO CACAT KAKI CACAT TANGAN CACAT MUKA CACAT SEMUAHNY PARAH BET SI KONTOL LO JUGA CACATAN PASTI NANAHAN JUGA,UDH MENDING LO BUNDIR DEH JADI BEBAN ORG DOANG BEGO NGERUGIN MASYARKAT BEGO BOCAH HINA BOCAH HARAM BOCAH AUTIS KEK LO MENDING MATI G COCOK BNGT LO IDUP BWGO BAPALO BILANGIN KALO G PNY DUIT GUSH NYOLONG DUIT ORG BEGO MAKANY KERJA JNGN JD PENGANGGURAN TOLOL KELUARGA G BERGUNA NGAPAIN DI BANGUN SI AELAH TOLOL NYUSAHAIN MASYARAKT AJ BUAT MAK LO JANGAN KEBANYAKN NGUTANG MALU AMA TETANGGA UTANH UDH NUMPUK GTU MENDING LO SURU MAK LO JUAL DIRI DIPINGGIR JALAN BIAR BISA BIAYAIN KEHIDUPAN LO SAMA BAPALO YG KANG COLONG.KELUARGA G BERGUNA INI MENDING HRS DI BASMI DARI DUNIA BIAR G NYUSAHIN WARGA LO.KEKNY LO PINDAH JG GAADA YG MAU NERIMA ORG KLUARGA LO KELURAGA NYUSAHIN G GUNA BNGT JD ORG,UDH LO SURU TUH ORG TUA LO JUAL DIRI SAMA LO JG JUAL DIRI BIAR G NYUSAIN MASYRAKT TRS TOLOL**"
                        )


@joo_cmd(pattern="ykk(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**YAILAH KOSA KATA MUTER MUTER BIAR APA BANG NIH GUA BLGIN SAMA LU HIDUP LU UDH DI KENDALIIN  AMA TUAN LU GEGARA LU SERING NONGKRONG DI TMPT DUKUN BUAT BISA BANYAK PUNYA KOSA KATA KRNA LU MISKIN PIKIRAN JDI MNT BANTUAN BIAR AD FIKIRAN UNTUK PUNYA KOSA KATA LU DI SURUH MINUM DARAH MENS NAMPUNG TAI ORANG KE MULUT LU, DEMI LU BISA PINTER MIKIR KOSA KATA SAMPE MAU AJ DI SURUH YG JOROK JOROK YH KRNA ITU TDI OTAK LU MISKIN FIKIRAN PENDIDIKAN LU DI BAWAH RATA RATA GEGARA LU DI SEKOLAH DI SLB SEKOLAH LUAR BIASA ATAU GA DI SEKOLAH GAJA MADA JDI OM OM GIRRANG YG SUKA MAIN DI OYO SAMA LONTE DI SEKOLAHAN LU KAN IYA GUA PAHAM LU GA MAMPU NYEWA LONTHE, UDH MISKIN FIKIRAN RENDAH PENDIDIKAN MISKIN HARTA PULA SATU LAGI MISKIN GANTENG ANJING, MUKA LU SI KEBNYAKAN BOPENGNYA JERAWAT BATU GEDE GEDE MERAH MERAH SEKALINYA PECAH KELUAR NANAH KOMEDONYA BANYAK BET BANYAK SAMPE MENGHITAM PORI PORINYA GEDE MUKANYA HITAM DEKIL ITU EFEK**")


@joo_cmd(pattern="kel(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**KELAMAAN MISKIN JDIGA MAMPU BELI SKINCATE BELI AIR MAWAR YG HARGA 5K DOANG AJA GA SANGGUP YA APA LAGI BELI SERUM YG PALING MURAH 50 RIBUAN ANJIR ITU ITU EFEK KEBIASAAN PAKEK HN TEMULAWAK POKOKNYA KEBANYAKAN MERKURI**"
                        )


@joo_cmd(pattern="yen(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**YA ELAH NI GUA KASIH TAU YA, HEY JAMET PARAKAN 01 YG MUKANYA KEK CAPUNG MASAGASKAR, LU ITU KALO LEMBEK JAN SOK SOK AN MAU REP REP AN SAMA GUA BEGO, LU AJA MASIH MINTA UANG SAMA EMAK LU, UDH EMAKLU NGANGKANG SANA SINI KAGA DI BAYAR, MEMEK BAU TERASI, MATA KELUAR SATU, TANGAN BUNTUNG SATU, KAKINYA AJA BURUK SEBELAH, NIH GUA KASIH TAU LAGI YA LU KLO MISALNYA, EMAK LU LAHI KEEJA ITU LU BANTUIN TOLOL, BUKANNYA MALAH NGELEM PINGGIR JALAN MULU BEGO, LEM AIBON LU ISEP ISEP KONTOL, OH IYA LUPA LU KAN CUMAN JADI!**"
                        )


@joo_cmd(pattern="bmm(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew, "**YAILAH BANG MENTANG MENTANG LU BERKONTOL KASIAN ADIK LU BANGUN NTR YG AD LU BUKAN WAR MALAH NGACENG CARI VCS DI BOT ANJAY, UDH INI KN UDH MAU LARUT MENDING LU SIAP SIAP PAKAIAN TUH LONTHE SEWAAN LU UDH NUNGGUIN LU DI DEPAN KOSANNYA YG KAYA GUBUG ITU SEWA MOBIL BIAR CWENYA PUAS JGN PAKAI BAJAI LU YG JELEK ITU JGN KELIATAN BANGET LU PENARIK BAJAII ATREK, BAHAHAHA UDH BANG GUA BAIK AMA LU ITU LIAT KONTOL LU DH BANGUN LONTHE SEWAAN LU YG SE JAM 2000 UDH NUNGGUIN LU BEGO PELER LU JGN LUPA DI CAT PUTIH DLU BIAR DIA GA NYESEL NGELIAT PELER  LU YG GOSONG KAYA TITIT ORG NEGRO!!**"
                        )


@joo_cmd(pattern="tbb(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew, "**YAILAHHH TOLOL BANGET BAPAK GUA SUNAT LU BELOM LAHIR BEGO JGN MALU MALUIN ALAHSIA DENGEN KETOLOLAN LU SO SO AN NGAKU NGAKU BAYARIN LU AJA SUNATNYA SUNAT MASALAH YG GRATISAN ITU YA KAN BEHH KRNA LU GA MAMPU BAYAR SUNAT SUNAT YG NUNGGU GILIRAN SAMPE LU GEMETARAN TERUS KABUR KRNA TKUT TITIT LU ILANG YA KAN UDH UDH SONO SUNAT LAGI AJ KNP? GA MAU?? KRNA GA MAMPU? KRNA TKUT TITIT NYA HABIS?? YAELAH LU GA COCOK PKEK KONTOL ATAU MEMEK LU COCOKNYA KAYA TETANGGA GUA MEMEK KONTOL GA PUNYA KRNA KONTOLNYA UDH DI CINCANGNYA GEGARA DEPRESI SAMA KAYA LU DEPRESI GA PUNYA DUIT PUNYA NYA HP HSIL COLONGAN KUOTA HASIL MALING WIFI TETANGGA**"
                        )


@joo_cmd(pattern="elp(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await edit_or_reply(typew,
                        "**P BG , EMANG LO PUNYA BAPAK.? ORANG BAPAK LO AJA MEINGGAL PAS WAKTU LO LAHIR TOLOL ,MAK LO JUGA YANG BEGO BEGO ITU MASI AJA NGELONTE BEGITU TOLOL MAKANYA KALO PUNYA ORANG TUA ITU YANG BENRAN NAPA JANGAN KAYA ORANG AUTIS BGITU TOLOL,MENDINH SURUH MAK LO CARI LAKI BARU YANG KAYA DIKIT TOLOL JANGAN CARI YANG MISKIN BEGO UDAH TAU IDUP LO MISKIN MASI AJA MAU NGE BEBANIN LAGI EKWK ,GUA TAU LO BUAT MAKAN JAM SEGINI AJA SUSAH TOLOL KARENA LU DARI KLUARGA YANG KURANG MAMPU DAN KURANG PERHATIAN DARI ORANG ORANG KARENA KLUARGA LO KAGA JELAS BEGOK ,UDAH LAH DARIPADA LO BEBAM MENDING LO KERJA TOLOL KASIAN MAK LO YANG AMA BAPAK BARU LO YANG KAGA BERGUNA ITU TOLOL BOCAH AMPAS BOCAH IDIOT BOCAH TOLOL, GUA TAU STIAP LO KLUAR ATAU PERGI KE TONGKRONGAN LO SELALU JADI BADUT KAN? APA GA CAPE LO JADI BADUT TOLOL? YAH BOCAH AMPAS IDIOT ,DI BADUTIN AJA MAU BAE GBLK**"
                        )



CMD_HELP.update(
    {
        "war4": f"𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}ykk\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}kel\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}yen\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}bmm\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}tbb\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: {cmd}elp\
        \n↳ : lihat sendiri\
        \n↳ **COBAIN AJA SAMA LU MEMEK!**.\
    "
    }
)
